name: CI

on:
    push:
    pull_request:

jobs:

    phpunit:
        name: PHPUnit with PHP ${{ matrix.php }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: [ '8.1', '8.2', '8.3' ]

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup PHP ${{ matrix.php }}
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}

            - name: Install composer dependencies
              uses: ramsey/composer-install@v2

            - name: Run test suite on PHP ${{ matrix.php }}
              run: vendor/bin/phpunit tests

    ecs:
        name: Easy Coding Standard
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ramsey/composer-install@v2
            - run: vendor/bin/ecs

    phpstan:
        name: PHPStan
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ramsey/composer-install@v2
            - run: vendor/bin/phpstan
