name: CI

on:
    push:
    pull_request:

jobs:

    phpunit:
        name: PHPUnit with PHP ${{ matrix.php }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: [ '8.1', '8.2', '8.3' ]

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup PHP ${{ matrix.php }}
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}

            - name: Install composer dependencies
              uses: ramsey/composer-install@v2

            - name: Run test suite on PHP ${{ matrix.php }}
              run: vendor/bin/phpunit tests --coverage-clover clover.xml

            - name: Make code coverage badge
              uses: timkrase/phpunit-coverage-badge@v1.2.1
              with:
                  coverage_badge_path: output/coverage.svg
                  push_badge: false

            - name: Git push to image-data branch
              uses: peaceiris/actions-gh-pages@v3
              with:
                  publish_dir: ./output
                  publish_branch: image-data
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  user_name: 'github-actions[bot]'
                  user_email: 'github-actions[bot]@users.noreply.github.com'

    ecs:
        name: Easy Coding Standard
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ramsey/composer-install@v2
            - run: vendor/bin/ecs

    phpstan:
        name: PHPStan
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ramsey/composer-install@v2
            - run: vendor/bin/phpstan
